server:
  port: 9000




#网关   服务的名称
spring:
  application:
    name: api-gateway




#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#自定义路由映射
zuul:
  routes:

    product-service: /apigateway/blockchain/**
  #    order-service: /apigateway/order/**
  #统一入口为上面的配置，其他入口忽略
#  ignored-patterns: /*-service/**

  #忽略整个服务，对外提供接口
#  ignored-services: product-service
