server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #declare that this is a server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false